version: '3.8' # Specify the Docker Compose file format version

services:
  aws-version-checker: # Define a service named 'aws-version-checker'
    build: . # Instruct Docker Compose to build the image from the Dockerfile in the current directory

    image: aws-test:compose # Use tag to differentiate from command-line image run (aws-test:cl)

    container_name: aws-test-compose # Assign a specific name to the container

    volumes:
      - ~/.aws:/root/.aws:ro

    #1
    # entrypoint: [""]
    # command: ["aws", "--version"]
    # command: ["ls", "-la"]
    # command: ["ls", "-la", "/root/.aws"] # command will list the contents of the /root/.aws directory

    #2
    command: ["--version"] # command will output the AWS CLI version to the console
    # and then the container will exit.
